export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_THEATER = "GET_THEATER";
export const THEATER_LOADING = "THEATER_LOADING";
export const THEATER_NOT_FOUND = "THEATER_NOT_FOUND";
export const GET_THEATERS = "GET_THEATERS";
export const THEATERS_LOADING = "THEATERS_LOADING";
export const THEATERS_NOT_FOUND = "THEATERS_NOT_FOUND";
